CREATE TABLE forms (
    form_id BIGINT NOT NULL AUTO_INCREMENT,
    title VARCHAR NOT NULL,
    submit_message VARCHAR,
    submit_channel VARCHAR NOT NULL,
    message_id VARCHAR,
    message_channel VARCHAR,
    expiration BIGINT NOT NULL DEFAULT -1,
    closed BOOLEAN NOT NULL DEFAULT FALSE,
    onetime BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (form_id)
);

CREATE TABLE FORM_FIELDS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    FORM_ID BIGINT NOT NULL,
    LABEL CHARACTER VARYING NOT NULL,
    MIN INTEGER DEFAULT 0 NOT NULL,
    MAX INTEGER DEFAULT 16 NOT NULL,
    PLACEHOLDER CHARACTER VARYING,
    REQUIRED BOOLEAN DEFAULT FALSE NOT NULL,
    "style" ENUM('SHORT', 'PARAGRAPH') DEFAULT 'SHORT' NOT NULL,
    INITIAL CHARACTER VARYING,
    PRIMARY KEY (ID),
    FOREIGN KEY (FORM_ID) REFERENCES FORMS(FORM_ID) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE form_submissions (
    "timestamp" BIGINT NOT NULL,
    user_id VARCHAR NOT NULL,
    form_id BIGINT NOT NULL,
    user_name VARCHAR NOT NULL,
    PRIMARY KEY ("timestamp")
);

CREATE INDEX FORM_SUBMISSIONS_USER_ID_IDX ON form_submissions (user_id,form_id);
